### PR TITLE
Backend-project-setup- Self-Sprint-1

### PR DESCRIPTION
**Pull request by Munalula-Sikazwe**
Created Project setup which includes writing project requirements and  folder structure. The setup includes the installation of  Fastapi and Unvicorn which is the ASGI server relevant for this project. This includes the authentication folder that includes user models and schemas.

### CODE REVIEW

**Review by askinss — COMMENTED** [review]
Good gitignore that puts into consideration other possible developer platforms.

**Comment by askinss** [comment]
@Munalula-Sikazwe  Is it possible to add unit testing to this?

**Comment by Munalula-Sikazwe** [comment]
Yes it is . I will .

**Comment by Munalula-Sikazwe** [comment]
Configured unit tests by integration pytest for testing and Httpx for internal requests.

**Comment by Munalula-Sikazwe** [comment]
Configured unit testing by integrating pytest

**Pull request closed without merging**
