### PR TITLE
Privacy settings

### PR DESCRIPTION
**Pull request by Vic-Orlands**
I have created a new PR

### CODE REVIEW

**Comment by askinss** [comment]
@heysolomon can you review, especially the codacy?

**Comment by heysolomon** [comment]
> @heysolomon can you review, especially the codacy?

okay

**Comment by heysolomon** [comment]
@askinss  I can see that there are issues coming from the ```README.md``` file because there were changes made to the file, @Vic-Orlands did you make changes to the file? Because from what I see, changes were made, and it doesn't follow the codacy's indentation rule. Check the main ```readme.md``` and the ```README.md``` file found in the backend's folder, the issues are from both files.

When you have the files open press ```ctrl + shift + p``` and search for ```ESLint: fix all auto-fixable problems``` and click enter; it should automatically fix the indentation issues.

On the other hand, I don't think you have the access rights to make changes to both files. I would suggest you revert all changes in both files since they are unrelated to your task.

**Comment by askinss** [comment]
@heysolomon thanks, @Vic-Orlands  can you follow the suggestions?

**Comment by peculiaruc** [comment]
@Vic-Orlands I will merge this PR, Pull and fix the README.md issues

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands I will merge this PR, Pull and fix the README.md issues

Okay, I will

**Comment by peculiaruc** [comment]
> Collaborator

Issues on README. Assign them to me to review.  Else document them and share them with me to update them.

**Comment by peculiaruc** [comment]
> > @Vic-Orlands I will merge this PR, Pull and fix the README.md issues
> 
> Okay, I will

Not You, I am doing that already

**Pull request merged**
