### PR TITLE
Frontend base setup #47

### PR DESCRIPTION
**Pull request by heysolomon**
@askinss  I have created the base setup for the React project. I have added the font from the Figma style guide as the default font style in the project; I added Tailwind CSS, redux-toolkit, formik, and yup, and I have fully configured the redux-toolkit and Tailwind CSS also.

### CODE REVIEW

**Comment by heysolomon** [comment]
@askinss can you hold on with the merge first? I need to fix the failed checks by Codacy

**Comment by akinsola-segun** [comment]
@heysolomon 

> 

That's so thoughtful of you.

**Comment by askinss** [comment]
@heysolomon  am still seeing some codacy failure.

**Comment by heysolomon** [comment]
> @heysolomon am still seeing some codacy failure.

yes I'm still on it, I will let you know once I have been able to fix it

**Comment by heysolomon** [comment]
@akinsola-segun I don't know if my checks have passed; I can't see the Codacy checks again

**Comment by askinss** [comment]
> @akinsola-segun I don't know if my checks have passed; I can't see the Codacy checks again

@heysolomon I can't find it again, this is great. Did the extension work?

**Comment by heysolomon** [comment]
> > @akinsola-segun I don't know if my checks have passed; I can't see the Codacy checks again
> 
> @heysolomon I can't find it again, this is great. Did the extension work?

I didn’t use an extension though, because I tried installing it and it didn’t work, all I did was to add eslint to the project and it showed me all the parts of the code I was getting wrong, then I corrected them all and I committed the changes and pushed

**Comment by heysolomon** [comment]
@askinss The checks have passed. I guess it is okay to be merged now

**Pull request merged**
